site_name: TAXPASTA
site_description: TAXonomic Profile Aggregation and STAndardisation
site_author: Moritz E. Beber, Maxime Borry, James A. Fellows Yates, and Sofia Stamouli
site_url: https://taxpasta.readthedocs.io/

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs/quick_reference
        - docs/tutorials
        - docs/how-tos
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

theme:
  logo: assets/images/taxpasta-logo-white-pastaonly.svg
  favicon: assets/images/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
      default_handler: python
  - awesome-pages
  - exclude:
      glob:
        - "*.ipynb"
        - "*.rmarkdown"
        - "*.qmd"
        - "*_snippets.md"
        - "docs/tutorials/taxpasta-tutorial/*"
        - "docs/how-tos/taxpasta-tutorial/*"

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://nfcore.slack.com/archives/C031QH57DSS
      name: "Join the nf-core Slack, channel #taxprofiler"
    - icon: fontawesome/brands/github
      link: https://github.com/taxprofiler
      name: taxprofiler organization

copyright: Copyright &copy 2022 Moritz E. Beber, Maxime Borry, James A. Fellows Yates, and Sofia Stamouli

repo_url: https://github.com/taxprofiler/taxpasta
repo_name: taxprofiler/taxpasta

watch:
  - src/taxpasta
