name: Test Suite

on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-slim]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # install

      - name: Check code style
        run: hatch run style:code

      - name: Check docstrings
        run: hatch run style:docstrings

      - name: Build documentation
        run: hatch run docs:build

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-slim, macos-latest, windows-latest]
        python-version: ["3.11", "3.13"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      # We install hatch without its GitHub Action here, because that causes an error
      # with the distribution check on MacOS and Windows.
      - name: Install hatch
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install hatch

      - name: Check distribution
        run: hatch run distribution:check

      - name: Audit dependencies
        run: hatch run audit:check

      - name: Check types
        run: hatch run types:check

      - name: Run unit tests
        run: hatch run +py=${{ matrix.python-version }} unit-tests:run -- --cov=taxpasta --cov-report=term-missing --cov-report=xml

      - name: Report coverage
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
